name: Build CI

# Trigger the workflow on push
on: [push]

jobs:
  Build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [16, 18]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node_version: ${{ matrix.node_version }}

    - name: Install NativeScript
      run: npm install -g nativescript

    - name: npm install and test
      working-directory: ./src
      run: |
        npm i
        npm run build
        npm run test

  Android:
    name: Android Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Base Setup
        working-directory: ./src
        run: |
          npm install -g nativescript
          npm i
          npm run preparedemo

      - name: Build Android
        run: npm run e2e:android

      # - name: Install Android sdkmanager
      #   run: |
      #     wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
      #     sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
      # - name: Install required Android tools
      #   run: |
      #     echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;${ANDROID_NDK}" > /dev/null
      # - name: Android Test
      #   run: |
      #     echo no | android create avd --force -n test -b armeabi-v7a
      #     emulator -avd test -no-audio -no-window &
      #     android-wait-for-emulator
      #     cd src && npm i && npm run tsc && cd ../demo && tns build android
      #     tns test android --justlaunch

  job2:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Base Setup
        working-directory: ./src
        run: |
          npm install -g nativescript
          npm i
          npm run preparedemo

      - name: Build iOS
        run: npm run e2e:ios
      # - name: iOS Test
      #   run: |
      #     cd src && npm i && npm run tsc && cd ../demo && tns build ios
      #     tns test ios --justlaunch
